#ifndef APP_EVENTS_H
#define APP_EVENTS_H

typedef enum
{
    EVT_NONE = 0,
    EVT_START,
    EVT_RESET,
    EVT_FAULT,
    EVT_SELF_OK,
    EVT_SELF_FAIL,
    EVT_MM_OK,
    EVT_GIMBAL_OK,
    EVT_THZ_LOCK,
    EVT_TIMEOUT,
    EVT_LOST,
    EVT_MM_RECOVER,
    EVT_NO_RECOVER,
    EVT_BBU_OFFLINE,
    EVT_BBU_NOT_READY,
    EVT_BBU_RECOVERED,
    EVT_BBU_DATA_STALE,
    EVT_THZ_OFFLINE,
    EVT_THZ_NOT_READY,
    EVT_THZ_RECOVERED,
    EVT_GIMBAL_OFFLINE,
    EVT_GIMBAL_NOT_READY,
    EVT_GIMBAL_RECOVERED,
    EVT_GIMBAL_ERROR,
    EVT_REACQUIRE_OK,
    EVT_REACQUIRE_TIMEOUT,
    EVT_REACQUIRE_REALIGN,
    EVT_RECOVERY_OK,
    EVT_RECOVERY_TIMEOUT,
    EVT_TARGET_LOST,
    EVT_GIMBAL_ALIGN_TIMEOUT,
    EVT_COUNT
} app_event_t;

#endif
